# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureAndHumidityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=10)),
                ('temperature', models.CharField(max_length=5)),
                ('humidity', models.CharField(max_length=5)),
                ('lat', models.CharField(max_length=10)),
                ('lon', models.CharField(max_length=10)),
            ],
        ),
    ]
