# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2022-11-22 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatureandhumiditydata',
            name='accelX',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='temperatureandhumiditydata',
            name='accelY',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='temperatureandhumiditydata',
            name='accelZ',
            field=models.CharField(default='', max_length=10),
        ),
    ]
