# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2022-11-22 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221122_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureandhumiditydata',
            name='timestamp',
            field=models.CharField(max_length=26),
        ),
    ]
